### ISSUE TITLE
Example of using autocompletepridiction adapter with filterable 

### ISSUE THREAD

**Issue by burhankhanzada199888** [googlemaps/android-places-demos#1]
please make example of autocompletepridiction adapter with filterable to apply filter on returning list on autocompletepridiction response like in old sdk examples

**Comment by gavingt** [comment]
Agreed. We have five months to transition over to the new SDK and no idea how to implement this.

**Comment by amuramoto** [comment]
@gavingt Our [documentation](https://developers.google.com/places/android-sdk/) is fully updated with code samples and a [migration guide](https://developers.google.com/places/android-sdk/client-migration) is also available in the docs.

**Comment by amuramoto** [comment]
@burhankhanzada199888 Result filtering is covered in the [docs](https://developers.google.com/places/android-sdk/autocomplete#constrain_autocomplete_results) and location bias, location restrictions, and type filtering are all shown in AutocompleteTestActivity.java of this demo.

**Comment by gavingt** [comment]
@amuramoto This is barely covered in the documentation. What we need is an updated sample that does the same as this:

https://github.com/googlesamples/android-play-places/tree/master/PlaceCompleteAdapter

And this sample project is missing that.

**Comment by amuramoto** [comment]
@gavingt Can you elaborate on what's missing or glossed over in the documentation? It would be very helpful.
