### ISSUE TITLE
9012: Error while parsing 'fields' parameter: Unsupported field name 'opening_hours'. 

### ISSUE THREAD

**Issue by TommyLemon** [googlemaps/android-places-demos#10]
In the screen named "Current Place", if "OPENING HOURS" were chosen in the place fields, the api will throw such an exception: 
com.google.android.gms.common.api.ApiException: 9012: Error while parsing 'fields' parameter: Unsupported field name 'opening_hours'.

**Comment by amuramoto** [comment]
Opening hours is not supported for current place requests. Documented here:

https://developers.google.com/places/android-sdk/current-place#get-current

**Comment by wangela** [comment]
Will fix the demo to remove this deprecated field from the default call to findCurrentPlace.

**Comment by wangela** [comment]
Confirmed that the demo excludes OPENING_HOURS from the requested place fields when calling findCurrentPlace. This was fixed in PR #11 at [Line 66](https://github.com/googlemaps/android-places-demos/pull/11/files#diff-1f6f4db7d512d95a4b7c895888ef6bab)
