### ISSUE TITLE
Null object reference after initializing AutocompleteSupportFragment

### ISSUE THREAD

**Issue by ABhayBohra** [googlemaps/android-places-demos#12]
After putting this line

AutocompleteSupportFragment autocompleteSupportFragment = (AutocompleteSupportFragment) getSupportFragmentManager().findFragmentById(R.id.autocomplete_fragment);

I am getting "autocompleteSupportFragment" null

**Comment by wangela** [comment]
@ABhayBohra You should use findFragmentById(R.id.autocomplete_support_fragment) instead of referencing R.id.autocomplete_fragment
