### ISSUE TITLE
Where are the Android Places SDK Javadocs? 

### ISSUE THREAD

**Issue by marcoRS** [googlemaps/android-places-demos#13]
Hello, I'm having trouble finding the javadocs for this new library. Can someone please link me? It has always been the case for me that I have trouble downloading the source or javadocs in Android Studio , so I am wanting guidance on what is the best place to read the javadocs for this new Places SDK. 

For example when I try to look up the javadocs in AS I get the following info: 

<img width="983" alt="Screen Shot 2019-04-23 at 2 59 42 PM" src="https://user-images.githubusercontent.com/507510/56579281-71e9cd80-65d8-11e9-864c-98bf73a09ce7.png">

Note: I tried looking here: https://developers.google.com/android/reference/packages

**Comment by wangela** [comment]
Reference docs are at https://developers.google.com/places/android-sdk/reference

Full documentation including guides and samples are at https://developers.google.com/places/android-sdk/intro
