### ISSUE TITLE
Search suggestions are invalid

### ISSUE THREAD

**Issue by bartekkaminski** [googlemaps/android-places-demos#156]
Environment details

- . `'com.google.android.libraries.places:places:2.4.0'`
- Android 29/30

#### Steps to reproduce

  For the example from this library in the **KOTLIN** version (**ProgrammaticAutocompleteToolbarActivity**), I changed the data to search from my location. (you can see it in the attached code).
When I start typing the name of a street that is almost in the neighborhood, it doesn't find it.
When I almost enter the whole street name, it will find it in a different city.

It gives the impression that it is everywhere, but not where it should be.

#### Code example

```
val bias: LocationBias = RectangularBounds.newInstance(
        LatLng(18.55480, 54.34082),
        LatLng(18.72612, 54.42620)
)

val newRequest = FindAutocompletePredictionsRequest
        .builder()
        .setSessionToken(sessionToken)
        .setOrigin(LatLng(18.62556, 54.38044))
        .setLocationBias(bias)
        .setTypeFilter(TypeFilter.ADDRESS)
        .setQuery(query)
        .setCountries("PL")
        .build()
```

Looking at other implemented solutions that work very well my situation is very strange. I don't know where to look for the problem.

**Comment by arriolac** [comment]
Hi @bartekkaminski, looking at the code sample you shared, it looks like the value in `setCountries` should be "OM" and not "PL" based on the lat/lng information.

**Comment by arriolac** [comment]
Closing this. Please reopen if you are still having issues.
