### ISSUE TITLE
Did you init the PlacesClient? This is maybe the reason for your issues.

### ISSUE THREAD

**Issue by qasimabdani** [googlemaps/android-places-demos#16]
Did you init the PlacesClient? This is maybe the reason for your issues.

_Originally posted by @L3viAckerman in https://github.com/googlemaps/android-places-demos/issues/15#issuecomment-491333359_

**Comment by qasimabdani** [comment]
> Did you init the PlacesClient? This is maybe the reason for your issues.
> 
> _Originally posted by @L3viAckerman in [#15 (comment)](https://github.com/googlemaps/android-places-demos/issues/15#issuecomment-491333359)_

yes i initialize it on create method

**Comment by qasimabdani** [comment]
> Did you init the PlacesClient? This is maybe the reason for your issues.
> 
> _Originally posted by @L3viAckerman in [#15 (comment)](https://github.com/googlemaps/android-places-demos/issues/15#issuecomment-491333359)_



> Did you init the PlacesClient? This is maybe the reason for your issues.
> 
> _Originally posted by @L3viAckerman in [#15 (comment)](https://github.com/googlemaps/android-places-demos/issues/15#issuecomment-491333359)_

i did not init Place Client and am not using instant of Place client so there is no need ?

**Comment by amuramoto** [comment]
You need to also init the PlacesClient. See step 2 here:

https://developers.google.com/places/android-sdk/start#connect-client
