### ISSUE TITLE
Unable to get postal_code of the Place for some of the Locations

### ISSUE THREAD

**Issue by Sudhakaraks03** [googlemaps/android-places-demos#17]
Hai 
I'am trying get postal_code of the location for which i selected from autocomplete predictions, but if Address contains postal_code then only i'am able get it through Address Component, but i want postal_code for all the locations which i select from the  autocomplete prediction.
Example:
 search for RT Nagar,  Bangalore 
i'am getting some suggestions out of  those some of them don't have Pin code like
 RT Nagar, Bagalore, Karnataka, India don't has any pin code in Address component 
[Please reply to my query ASAP]

**Comment by amuramoto** [comment]
Likely cause is that some places don't have a postal code in the data we're serving
