### ISSUE TITLE
Session for autocomplete is not working

### ISSUE THREAD

**Issue by bartekkaminski** [googlemaps/android-places-demos#171]
Environment details
- 'com.google.android.libraries.places:places:2.4.0'
- Android 29/30

I wanted to test in DEMO how sessions with Token for autocomplete work.

Whichever combination I take, I think the session isn't working.

When I type the address and look at the requests for the Places API, it is equal to the number of characters entered.

Shouldn't there be one session and one request?

**Comment by arriolac** [comment]
It depends on how you are creating the token—it should be done once per session. Can you share more code snippets?
