### ISSUE TITLE
Sessiontoken not working

### ISSUE THREAD

**Issue by Luuk99** [googlemaps/android-places-demos#18]
Hi,

I have been struggling with the session token for a while, nothing seems to work. 
Therefore I tried your demo app but enabling session token does not make a difference, they still charged me 18 requests for 1 address autocomplete. 

Do you have any idea why it is not working or am I the only one for which this is not working? Do I need to edit something in my Google API Console?

Kind regards, 
Luuk

**Comment by amuramoto** [comment]
Please post debugging questions to our StackOverflow tag. Thanks!

https://stackoverflow.com/questions/tagged/google-maps
