### ISSUE TITLE
Autocomplete Address Form sample: Multiple AC intents can open

### ISSUE THREAD

**Issue by wangela** [googlemaps/android-places-demos#181]
There is a bug right now though where tapping on address1Field in quick succession will launch multiple AC. 

_Originally posted by @arriolac in https://github.com/googlemaps/android-places-demos/pull/167#discussion_r621705172_

Bug location: [AutocompleteAddressActivity.java](https://github.com/googlemaps/android-places-demos/blob/84e86f852269d61f04f59ae302e5745570bf92d2/demo-java/app/src/gms/java/com/example/placesdemo/AutocompleteAddressActivity.java)

Proposed solution: [PR comment](https://github.com/googlemaps/android-places-demos/pull/167#discussion_r622287434)

**Comment by kikoso** [comment]
The following PR fixes this issue:

https://github.com/googlemaps/android-places-demos/pull/449
