### ISSUE TITLE
Can't load search results

### ISSUE THREAD

**Issue by niranjansheshadri** [googlemaps/android-places-demos#19]
Hello,

I am trying to implement the Google Places Autocomplete API sometimes I am able to get location list but sometimes I get **"can't load search results"** message. Even I tried the demo app there also I have the same issue. Can you please help whether I am missing any configurations or what I am doing wrong.

Thank you

**Comment by amuramoto** [comment]
Please post debugging questions to our StackOverflow tag. Thanks!

https://stackoverflow.com/questions/tagged/google-maps

**Comment by vxplore** [comment]
I am having the same problem. Can anybody share a solution

**Comment by alex8530** [comment]
you must have a billing account in google play console ..

**Comment by Atr07** [comment]
> you must have a billing account in google play console ..

For testing the places api should we need to add billing account ?

For me in the onerror method of setOnPlaceSelectedListener the status message is null and status code 16.

**Comment by rausn222** [comment]
I am getting the same error but I am having billing account.

**Comment by IrinaStojanoska** [comment]
Go to Google Cloud Platform -> Credentials and restrict API key
