### ISSUE TITLE
PlaceSelectionListener is not triggerred

### ISSUE THREAD

**Issue by billylo1** [googlemaps/android-places-demos#22]
Tried to follow your demo to use PlaceSelectionListener in AutocompleteTestActivity; but both onPlacesSelected and onError were never fired...

I thought it may be related to [this](https://stackoverflow.com/questions/34507708/onplaceselectedlistener-of-supportplaceautocompletefragment-not-fired-inside-vie), but still no luck trying to do something like this.
```

  @Override
  protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent intent) {

    super.onActivityResult(requestCode, resultCode, intent);
    autocompleteSupportFragment.onActivityResult(requestCode, resultCode, intent);
```

**Comment by amuramoto** [comment]
@wangela Can you take a look at this?
