### ISSUE TITLE
Leaked GCP API Keys - Places, Maps APIs

### ISSUE THREAD

**Issue by ronsivan1** [googlemaps/android-places-demos#299]
#### Environment details

1. Specify the API at the beginning of the title - Places API, Maps API
2. OS type and version - Android 11
3. Library version and other environment information - [secrets-gradle-plugin](https://github.com/google/secrets-gradle-plugin) 2.0.0

### The error

I've received the following error in Play Console:
Errors found. Fix before releasing to production.
Leaked GCP API Keys - Your app contains exposed Google Cloud Platform (GCP) API keys.

![image](https://user-images.githubusercontent.com/45716037/145979828-68c7cc6d-e2bd-4dd5-87b4-345d1393d757.png)

### What I've tried

I've applied all the best practices mentioned in [Securing an API key](https://cloud.google.com/docs/authentication/api-keys#securing_an_api_key) and of course I've added [API key restrictions.](https://cloud.google.com/docs/authentication/api-keys#api_key_restrictions)

I'm using the [secrets-gradle-plugin](https://github.com/google/secrets-gradle-plugin) latest version as of now - 2.0.0, in order to hide my API key, I've followed the instructions in [this video](https://www.youtube.com/watch?v=X8lYNW_Or2o) and my API key is stored inside the `local.properties` and the `BuildConfig.java` file. unfortunately this isn't enough for google and they still won't let me release my app because of this silly error.

How do I fix this error?

Does this prevent me from publishing my app on Internal Testing or Closed Testing?

Thanks.

**Comment by arriolac** [comment]
You can ignore that warning if you have added restrictions to your API key. See [Remediation for Exposed GCP API Keys](https://support.google.com/faqs/answer/9287711).
