### ISSUE TITLE
Error: Program type already present: com.google.android.libraries.places.api.internal.impl.net.pablo.AutocompletePredictionResult$StructuredFormatting" after adding new libraries

### ISSUE THREAD

**Issue by eriknyk** [googlemaps/android-places-demos#3]
I just added:

```
   implementation ('com.google.android.libraries.places:places:1.0.0') {
        exclude module: 'support-v4'
    }
    implementation ('com.google.android.libraries.places:places-compat:1.0.0') {
        exclude module: 'support-v4'
    }
```

And I got the following error:

```
AGPBI: {"kind":"error","text":"Program type already present: com.google.android.libraries.places.api.internal.impl.net.pablo.AutocompletePredictionResult$StructuredFormatting","sources":[{}],"tool":"D8"}
```

Any help will be appreciated.
Thanks in advance.

the only one related thing that I've found on entirely internet (using google of course) was:

http://qaru.site/questions/17030061/google-places-api-program-type-already-present-autocompletepredictionresult

and it is also answered.

**Comment by amuramoto** [comment]
This is because you are including both places and places-compat. You must remove one of them.

**Comment by joelmmx** [comment]
If you remove the second one: com.google.android.libraries.places:places-compat:1.0.0 the project doesn't compile.
Any idea??
@eriknyk , could you resolve it ?

**Comment by kamilwyszynski** [comment]
I have the same problem and removing one of them doesn't solve the problem.
I left the com.google.android.libraries.places:places:1.0.0 and the error is exactly the same.
What should I do?
@eriknyk

**Comment by dharmeshrathore** [comment]
i am having the same problem

**Error: Program type already present: com.google.android.libraries.places.api.internal.impl.net.pablo.AutocompletePredictionResult$StructuredFormatting**

what should i do?

**Comment by amuramoto** [comment]
@kamilwyszynski @dharmeshrathore Can you provide a link to your gradle file?

**Comment by McKabue** [comment]
Same problem here

**Comment by amuramoto** [comment]
@McKabue can you provide a link to your gradle file?

**Comment by jwilly12** [comment]
I have the same issue,  what was the solution?

**Comment by asmodeus78** [comment]
Same problem any solution found?

**Comment by jwilly12** [comment]
It was a library issue. Google is confusing with their new Places SDK migration description.
But I fixed the issue doing the following:

In Gradle App dependencies
implementation 'com.google.android.libraries.places:places:1.1.0'  // Remove 
implementation 'com.google.android.libraries.places:places-compat:1.1.0'  // Add 

*** In activity 
import com.google.android.libraries.places.api.net.PlacesClient; // Remove
import com.google.android.libraries.places.api.Places;  // Remove

*** Remove all com.google.android.gms.location.places and replace with:

import com.google.android.libraries.places.compat.AutocompletePredictionBufferResponse;  // New
import com.google.android.libraries.places.compat.AutocompletePrediction; //New
import com.google.android.libraries.places.compat.AutocompleteFilter;  //New
import com.google.android.libraries.places.compat.GeoDataClient;  //New
import com.google.android.libraries.places.compat.Place;  //New  
import com.google.android.libraries.places.compat.Places;  //New 
import com.google.android.libraries.places.compat.PlaceBufferResponse;  //New

**Comment by amuramoto** [comment]
thanks for the info @jwilly12!

**Comment by eriknyk** [comment]
@kamilwyszynski  nope, I have not look to get com.google.android.libraries.places.compat working,
I spend about middle day trying to get this working, and after that I decided to rewrite the implementation with using new api so get rid of places.compat, and rewrite the code took in my case half hour.

**Comment by rufinex** [comment]
Duplicate class com.google.android.libraries.places.api.internal.impl.net.pablo.AutocompletePredictionResult found in modules classes.jar (com.google.android.libraries.places:places-compat:1.1.0) and classes.jar (com.google.android.libraries.places:places:1.1.0)

It's impossible to solve this duplicity until a solution to this problem appears, I'll continue using 'com.google.android.gms: play-services-places: 16.1.0'

**Comment by AmritpalSingh5** [comment]
Just comment this 'com.google.android.libraries.places:places:1.0.0' use only this 'com.google.android.libraries.places:places-compat:1.0.0'  issue will resolved.
