### ISSUE TITLE
Keyboard doesn't show up automatically in Android API 28

### ISSUE THREAD

**Issue by gavingt** [googlemaps/android-places-demos#4]
In Android APIs prior to 28, when you press the "OPEN ACTIVITY" button, the keyboard shows up automatically and the user can begin typing immediately. However, in API 28 the user has to click the search bar before they can begin typing. This is clearly an inferior user experience.

**Comment by amuramoto** [comment]
Please open a bug for this in the Issue Tracker for the SDK.

https://issuetracker.google.com/bookmark-groups/76561
