### ISSUE TITLE
Places: ProgrammaticPlacePredictions   apiException: 9012 : INVALID_REQUEST

### ISSUE THREAD

**Issue by Hamzaelmi** [googlemaps/android-places-demos#454]
Hello,

ProgrammaticPlacePredictions not working when implementing **programmatic** place predictions.

I tried the exact same code [programmaticPlacePredictions](https://github.com/googlemaps/android-places-demos/blob/6e5cb15aff1e909e7917029cfb8cb911322d21ce/snippets/app/src/main/java/com/google/places/PlaceAutocompleteActivity.java#L164) ->  apiException: 9012 : INVALID_REQUEST
I tried setting minimum properties: Token, query, TypesFilter -> apiException: 9012 : INVALID_REQUEST
I tried working with widget/fragment and it worked.

I am using Android Studio Dolphin | 2021.3.1 Patch 1 and a physical device Google Pixel 6.

Kind regards,
Hamza

**Comment by kikoso** [comment]
Hi @Hamzaelmi.

Could you send us the query that you are using for this request? I assume you set an API Key for your project properly.

**Comment by Hamzaelmi** [comment]
Hi @kikoso 

I used different kinds of queries like:

- 401 George St
- 401 George St, Sydney
- Crown st
- Christ

**Comment by kikoso** [comment]
@Hamzaelmi , is the call failing when you execute it on an Activity? Could you share the relevant code or the project here?

**Comment by rmazajev** [comment]
@Hamzaelmi If you are setting `typesFilter` make sure you convert string to lower case. I'm not sure why, but if I build `FindAutocompletePredictionsRequest` like this:
```kotlin
FindAutocompletePredictionsRequest.builder()
            .setTypesFilter(listOf(TypeFilter.ADDRESS.toString()))
            .setQuery(query)
            .build()
```
I'm getting `9012 : INVALID_REQUEST` error as well. 

But if I convert `TypeFilter` to lower case it works:
```kotlin
val request = FindAutocompletePredictionsRequest.builder()
            .setTypesFilter(listOf(TypeFilter.ADDRESS.toString().lowercase()))
            .setQuery(query)
            .build()
```

It's strange that google docs example [here](https://developers.google.com/maps/documentation/places/android-sdk/autocomplete#get_place_predictions) they do not convert it to lower case, it's misleading.

**Comment by kikoso** [comment]
Oh yeah, that can certainly be the case. This is already reported in the [issue tracker](https://issuetracker.google.com/issues/261035620).

**Comment by Hamzaelmi** [comment]
That was it, I confirm. Really cool finding @rmazajev
