### ISSUE TITLE
Are there any plans on adding Address Components field to the Place detail interface?

### ISSUE THREAD

**Issue by VeegaP** [googlemaps/android-places-demos#6]
I've noticed that the Android SDK for Places API is missing the Address Components field (as stated here: https://developers.google.com/places/android-sdk/place-data-fields), making it unfeasible to get the specific components of an address: we can only get a formatted address, which is the joined string of some of its components.

Are there any plans on making it available as it is already on the iOS SDK? It's a bummer having to rely on the web API just for a missing mapping on the mobile SDK.

**Comment by amuramoto** [comment]
Hi! Please open this as a feature request in our public issue tracker:

https://issuetracker.google.com/issues?q=componentid:188846
