### ISSUE TITLE
What are examples for initialQuery?

### ISSUE THREAD

**Issue by akodiakson** [googlemaps/android-places-demos#7]
For example, can I pass coordinates or is this intended more for human readable addresses?

If yes to lat/long, how should they be formatted?

The docs here, just say that it's an "initial query", but don't really indicate a meaning:
https://developers.google.com/places/android-sdk/reference/com/google/android/libraries/places/widget/Autocomplete.IntentBuilder.html#setInitialQuery(java.lang.String)

**Comment by amuramoto** [comment]
This is intended to be a human readable query string
