### ISSUE TITLE
Why i am getting this, i import as you described.

### ISSUE THREAD

**Issue by dharmeshrathore** [googlemaps/android-places-demos#9]
I am getting this, Please Help.

Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Could not determine artifacts for androidx.recyclerview:recyclerview:1.0.0-rc01
Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/recyclerview/recyclerview/1.0.0-rc01/recyclerview-1.0.0-rc01.aar'.
Could not HEAD 'https://dl.google.com/dl/android/maven2/androidx/recyclerview/recyclerview/1.0.0-rc01/recyclerview-1.0.0-rc01.aar'.
Connect to dl.google.com:443 [dl.google.com/172.217.160.238] failed: Connection timed out: connect
Connection timed out: connect

**Comment by amuramoto** [comment]
can you post a link to your gradle file?

**Comment by amuramoto** [comment]
closing due to lack of response

**Comment by dharmeshrathore** [comment]
@amuramoto Sorry for the late reply..
Let me share my gradle fle....

```
**apply plugin: 'com.android.application'
``
android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.example.placesdemo"
        minSdkVersion 17
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        resValue "string", "places_api_key", (project.findProperty("PLACES_API_KEY") ?: "")
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-alpha3'
    implementation 'com.google.android.libraries.places:places-compat:1.0.0'
    implementation "com.android.support:support-core-utils:27.1.0"
}**

```

**Comment by amuramoto** [comment]
Is there a stacktrace available when it crashes?

**Comment by dharmeshrathore** [comment]
@amuramoto 
i did no change my code and in my gradle but its started working like magic :D
BTW thanks for the support.

**Comment by amuramoto** [comment]
Magic is always a good thing =)
